name: Gradle Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.312'
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -iS
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/libs/*"
          allowUpdates: true
          tag: "latest"
